### ISSUE TITLE
Add AutoPrefixer

### ISSUE THREAD

**Issue by dannyrb** [OHIF/react-viewerbase#83]
When adding a style like:

`user-select: none;`

I currently need to make sure to include all appropriate vendor prefixes:

```css
.no-select {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

In a perfect world, I would lean on something like https://github.com/postcss/autoprefixer so I don't need to remember in which stage of adoption each feature is in.
